<a href="https://colab.research.google.com/github/IshwaryaLaksh/DATA-Ques-1/blob/main/6_3_Python_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [23 30 37 44 51]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# you can take matrix input from user or you can directly define the matrix and give input to the function
# reference for creating input - https://stackoverflow.com/questions/12293208/how-to-create-a-list-of-lists

# you can free to change all these codes/structure
# here A and B are list of lists

def matrix_mul(A, B):
    for i in range(len(A)):
      for j in range(len(B[0])):
        for k in range(len(B)):
          result[i][j] += A[i][k] * B[k][j]     
    return(result)
    


In [ ]:
print("enter the number of rows for first matrix: ")
R1 = int(input())
print("enter the number of columns for first matrix: ")
C1 = int(input())
print("enter the number of rows for second matrix: ")
R2 = int(input())
print("enter the number of columns for second matrix: ")
C2 = int(input())
A = [[int(input()) for y in range(C1)] for x in range(R1)]###MATRIX INPUT SYNTAX
B = [[int(input()) for y in range(C2)] for x in range(R2)]
result = [[ 0 for y in range(C2)] for x in range(R1)]###RESULT MATRIX SYNTAX
matrix_mul(A, B)


enter the number of rows for first matrix: 
2
enter the number of columns for first matrix: 
2
enter the number of rows for second matrix: 
2
enter the number of columns for second matrix: 
2
1
2
3
4
1
2
3
4


[[7, 10], [15, 22]]

<h3> Q2: Replace the digits in the string with #</h3>

consider a string that will have digits in that, we need to remove all the not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [ ]:
import re
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# try to complete this question using regular expressions
# you can free to change all these codes/structure
# String: it will be the input to your program
# https://www.w3schools.com/python/python_regex.asp

def replace_digits(String):
    r = ''.join('#' for i in String if i.isdigit())
    return(r) # modified string which is after replacing the # with digits
    

In [ ]:
String = input()
replace_digits(String)

nckj12345xn


'#####'

<h3> Q3: Filling the missing values in the specified formate</h3>
You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 
<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4

</pre>



In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings
#run your code in the function for each of the inputs mentioned above and make sure that you get the same results

# you can free to change all these codes/structure
def curve_smoothing(string):
    # your code
    index_of_non_empty_cells_list = []

    split_string = string.split(',')
    
    for i in range(len(split_string)):
        if split_string[i] != '_':
            index_of_non_empty_cells_list.append(i)
            
    # add the length of the original list to index_of_non_empty_cells_list
    index_of_non_empty_cells_list.append(len(split_string) - 1)
    
    #print(index_of_non_empty_cells_list)
    
    # Loop over the index_of_non_empty_cells_list to modify the original list by filling up empty slots
    
    start = 0
    
    for ele in index_of_non_empty_cells_list:
        # Whenever there is a missing value, add the proceeding value and the immediately next available value
        # and divide it by the number of missing values.
        # Calculate the cumulative_sum of available non-empty cells.
        cumulative_sum_prev_and_next_value = int(split_string[ele]) if split_string[ele] != '_' else 0
        cumulative_sum_prev_and_next_value += int(split_string[start]) if split_string[start] != '_' and start != ele else 0
#       print(cumulative_sum_prev_and_next_value)
        # Divide the cumulative_sum of prev and next value by the number of missing values
        integer_to_replace = cumulative_sum_prev_and_next_value // (ele - start + 1)
        split_string = [integer_to_replace if start <= x <= ele else split_string[x] for x in range(len(split_string))]
        start = ele
    return split_string#list of values

    

In [ ]:
S=  "_,_,30,_,_,_,50,_,_"
smoothed_values= curve_smoothing(S)
print(smoothed_values)

[10, 10, 12, 12, 12, 12, 4, 4, 4]


<h3> Q4: Given two sentances S1, S2</h3>
You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
## c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [1]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings

# you can free to change all these codes/structure
def string_features(S1, S2):
    # your code
    # Split the words of the sentences and put the words in a set
    S1_words = set(S1.split())
    S2_words = set(S2.split())
    # Use set intersection operation to get the common words between 2 sets and compute the length of the resultant set
    a = len(S1_words & S2_words)
    # Use set difference operation to get the words that present in either of the set and display the words as a list
    b = set(S1_words) - (set(S2_words))
    b_l = list(b)
    c = set(S2_words) - (set(S1_words))
    c_l = list(c)
    return a, b_l, c_l





In [4]:
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
a, b_l, c_l = string_features(S1, S2)
print(a)
print(b_l)
print(c_l)


7
['5', 'F', 'first']
['S', 'second', '3']
